//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoContasV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCCC00Entities : DbContext
    {
        public DBCCC00Entities()
            : base("name=DBCCC00Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBCCC_001_USUA> TBCCC_001_USUA { get; set; }
        public virtual DbSet<TBCCC_002_ESTA_CIVI> TBCCC_002_ESTA_CIVI { get; set; }
        public virtual DbSet<TBCCC_003_ENDE> TBCCC_003_ENDE { get; set; }
        public virtual DbSet<TBCCC_004_TELE> TBCCC_004_TELE { get; set; }
        public virtual DbSet<TBCCC_005_CONT> TBCCC_005_CONT { get; set; }
        public virtual DbSet<TBCCC_006_FATU> TBCCC_006_FATU { get; set; }
    }
}
