//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoContasV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCCC_001_USUA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBCCC_001_USUA()
        {
            this.TBCCC_005_CONT = new HashSet<TBCCC_005_CONT>();
        }
    
        public int COD_USUA { get; set; }
        public Nullable<int> COD_ESTA_CIVI { get; set; }
        public Nullable<int> COD_ENDE { get; set; }
        public Nullable<int> COD_TELE { get; set; }
        public string NOM_USUA { get; set; }
        public string NOM_SEXO { get; set; }
        public string NUM_CPF_CNPJ { get; set; }
        public string NUM_RG { get; set; }
        public string DES_EMAIL { get; set; }
        public string NUM_SENH { get; set; }
        public string NOM_ORGA_EMIS { get; set; }
        public string NOM_ESTA_EMIS { get; set; }
        public string NOM_MAE { get; set; }
        public string NOM_PAI { get; set; }
        public string DES_NATU { get; set; }
        public Nullable<System.DateTime> DAT_INCL_USUA { get; set; }
        public Nullable<System.DateTime> DAT_ALTE_USUA { get; set; }
        public System.DateTime DAT_NASC_USUA { get; set; }
        public string IND_STAT_USUA { get; set; }
        public Nullable<bool> IND_CONS { get; set; }
        public Nullable<bool> IND_INCL { get; set; }
        public Nullable<bool> IND_ALTE { get; set; }
        public Nullable<bool> IND_EXCL { get; set; }
    
        public virtual TBCCC_002_ESTA_CIVI TBCCC_002_ESTA_CIVI { get; set; }
        public virtual TBCCC_003_ENDE TBCCC_003_ENDE { get; set; }
        public virtual TBCCC_004_TELE TBCCC_004_TELE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCCC_005_CONT> TBCCC_005_CONT { get; set; }
    }
}
