//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoContasV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCCC_003_ENDE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBCCC_003_ENDE()
        {
            this.TBCCC_001_USUA = new HashSet<TBCCC_001_USUA>();
        }
    
        public int COD_ENDE { get; set; }
        public string NUM_CEP { get; set; }
        public string DES_LOGR { get; set; }
        public string NUM_NUME { get; set; }
        public string DES_COMP { get; set; }
        public string DES_BAIR { get; set; }
        public string DES_CIDA { get; set; }
        public string DES_ESTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCCC_001_USUA> TBCCC_001_USUA { get; set; }
    }
}
