//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoContasV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCCC_005_CONT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBCCC_005_CONT()
        {
            this.TBCCC_006_FATU = new HashSet<TBCCC_006_FATU>();
        }
    
        public int COD_CONT { get; set; }
        public int COD_USUA { get; set; }
        public string DES_CONT { get; set; }
        public string NOM_USUA_CONT { get; set; }
        public string NUM_AGEN { get; set; }
        public string NUM_CONTA { get; set; }
        public string NUM_DAC_CONT { get; set; }
        public string COD_BANC { get; set; }
        public string NUM_CNPJ_CPF { get; set; }
        public string DESC_SENH_CONT { get; set; }
        public System.DateTime DAT_INCL_CONT { get; set; }
        public System.DateTime DAT_ALTE_CONT { get; set; }
        public string IND_STAT_CONT { get; set; }
        public Nullable<int> NUM_FATU_ABER { get; set; }
    
        public virtual TBCCC_001_USUA TBCCC_001_USUA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCCC_006_FATU> TBCCC_006_FATU { get; set; }
    }
}
