//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoContasV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCCC_004_TELE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBCCC_004_TELE()
        {
            this.TBCCC_001_USUA = new HashSet<TBCCC_001_USUA>();
        }
    
        public int COD_TELE { get; set; }
        public string NUM_DDI_CELU { get; set; }
        public string NUM_DDD_CELU { get; set; }
        public string NUM_TELE_CELU { get; set; }
        public string NUM_DDI_FIXO { get; set; }
        public string NUM_DDD_FIXO { get; set; }
        public string NUM_TELE_FIXO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBCCC_001_USUA> TBCCC_001_USUA { get; set; }
    }
}
